joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/sw/eb/sw/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/sw/eb/sw/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/sw/eb/sw/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/joblib/numpy_pickle.py", line 524, in load_temporary_memmap
    obj = load(filename, mmap_mode)
  File "/sw/eb/sw/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/joblib/numpy_pickle.py", line 585, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/sw/eb/sw/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/joblib/numpy_pickle.py", line 504, in _unpickle
    obj = unpickler.load()
  File "/sw/eb/sw/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/sw/eb/sw/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/joblib/numpy_pickle.py", line 342, in load_build
    self.stack.append(array_wrapper.read(self))
  File "/sw/eb/sw/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/joblib/numpy_pickle.py", line 185, in read
    array = self.read_mmap(unpickler)
  File "/sw/eb/sw/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/joblib/numpy_pickle.py", line 158, in read_mmap
    marray = make_memmap(unpickler.filename,
  File "/sw/eb/sw/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/joblib/backports.py", line 45, in make_memmap
    raise NotImplementedError(
NotImplementedError: 'joblib.backports.make_memmap' should not be used if numpy is not installed.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/user/sharkmanhmz/latentcor_py/latentcor_py/interpolation/ipol_33.py", line 35, in <module>
    value_NN = Parallel(n_jobs=68)(delayed(NN_par)(i) for i in range(len(points_NN_tau_grid)))
  File "/sw/eb/sw/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/sw/eb/sw/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/sw/eb/sw/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/sw/eb/sw/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/sw/eb/sw/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.
